site_name: Getting Started with WireGuard VPN
site_url: "https://cghuisunshine.github.io/wiregurad_setup/"
repo_url: "https://github.com/cghuisunshine/wiregurad_setup.git"
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/code-branch
  favicon: assets/images/code-branch-solid.svg
  features:
    - navigation.footer
    - content.code.copy
  palette:
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
nav:
  - Home: index.md
  - Getting Started: part1.md
  - Configuring the Server: part2.md
  - Configuring Clients: part3.md
  - Starting the VPN & Connecting: part4.md
  - Troubleshooting: troubleshooting.md
  - Glossary: glossary.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables

extra_css:
  - assets/style.css

copyright: Copyright &copy; - 2025 Peter Chen & Ryan Bow